#!name=Truecaller Premium
#!desc=By: Hoan IT

[Script]

#Truecaller
#hostname = premium*.truecaller.com
Truecaller = type=http-response,pattern=^https://premium-(.+)\.truecaller\.com/v\d/(subscriptions|products\/apple),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/trickerchannel/shadowrocket/refs/heads/main/truecaller.js

[MITM]
hostname = %APPEND% premium*.truecaller.com, sub.store, api.revenuecat.com
